package com.esoft.emobile.domain.model

data class Tag(
    val etiqueta: String = "",
    val chaveAcesso: String = "",
    val nf: String = "",
    val serie: String = "",
    val volumes: Int = 0,
    val item: String = "",
    val emitCnpj: String = "",
    val emitNome: String = "",
    val emitCidade: String = "",
    val emitUf: String = "",
    val destCnpj: String = "",
    val destNome: String = "",
    val destLogradouro: String = "",
    val destNumero: String = "",
    val destCep: String = "",
    val destCidade: String = "",
    val destUf: String = "",
    val orgSigla: String = "",
    val dstSigla: String = "",
    val dstRota: String = "",
    val dstParceiro: String = "",
    val dstShopping: Boolean = false,
    val dstCapital: Boolean = false,
    val orgTitulo: String = "",
)

data class Nf(
    val chaveAcesso: String = "",
    val nf: String = "",
    val serie: String = "",
    val volumes: Int = 0,
    val emitCnpj: String = "",
    val emitNome: String = "",
    val emitCidade: String = "",
    val emitUf: String = "",
    val destCnpj: String = "",
    val destNome: String = "",
    val destLogradouro: String = "",
    val destNumero: String = "",
    val destCep: String = "",
    val destCidade: String = "",
    val destUf: String = "",
    val orgSigla: String = "",
    val dstSigla: String = "",
    val etiquetas: List<Tag> = emptyList())
